services:
  backend:
    build:
      context: ./rp-back
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ConnectionStrings__DefaultConnection=Server=${SERVER_HOST},${SERVER_PORT};Database=${DATABASE_NAME};User Id=${DATABASE_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - CloudflareR2__AccessKey=${R2_ACCESS_KEY}
      - CloudflareR2__SecretKey=${R2_SECRET_KEY}
      - CloudflareR2__BucketName=${R2_BUCKET_NAME}
      - CloudflareR2__ServiceUrl=${R2_SERVICE_URL}
      - CloudflareR2__PublicDomain=${R2_PUBLIC_DOMAIN}
    ports:
      - "8080:8080"
    depends_on:
      - database
    develop:
      watch:
        - action: sync
          path: ./rp-back
          target: /app
          ignore:
            - bin/
            - obj/
        - action: rebuild
          path: ./rp-back/rp-back.csproj

  frontend:
    build:
      context: ./rp-front
      dockerfile: Dockerfile.dev
    environment:
      - JWT_KEY=${JWT_KEY}
      - BACKEND_URL=http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./rp-front
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./rp-front/package.json

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: